export let Weapons = {
  simple_melee: {
    club: {
      name: 'Club',
      melee: true,
      damage: '1d4',
      damage_type: 'bludgeoning',
      properties: ['light'],
    },
    dagger: {
      name: 'Dagger',
      melee: true,
      damage: '1d4',
      damage_type: 'piercing',
      properties: ['finesse', 'light', 'thrown (range 20/60)'],
    },
    greatclub: {
      name: 'Greatclub',
      melee: true,
      damage: '1d8',
      damage_type: 'bludgeoning',
      properties: ['two-handed'],
    },
    handaxe: {
      name: 'Handaxe',
      melee: true,
      damage: '1d6',
      damage_type: 'slashing',
      properties: ['light', 'thrown (range 20/60)'],
    },
    javelin: {
      name: 'Javelin',
      melee: true,
      damage: '1d6',
      damage_type: 'piercing',
      properties: ['thrown (range 30/120)'],
    },
    light_hammer: {
      name: 'Light Hammer',
      melee: true,
      damage: '1d4',
      damage_type: 'bludgeoning',
      properties: ['light', 'thrown (range 20/60)'],
    },
    mace: {
      name: 'Mace',
      melee: true,
      damage: '1d6',
      damage_type: 'bludgeoning',
      properties: [],
    },
    quarterstaff: {
      name: 'Quarterstaff',
      melee: true,
      damage: '1d6',
      damage_type: 'versatile (1d8)',
      properties: ['light'],
    },
    sickle: {
      name: 'Sickle',
      melee: true,
      damage: '1d4',
      damage_type: 'slashing',
      properties: ['light'],
    },
    spear: {
      name: 'Spear',
      melee: true,
      damage: '1d6',
      damage_type: 'piercing',
      properties: ['thrown (range 20/60)', 'versatile (1d8)'],
    },
  },
  simple_ranged: {
    light_crossbow: {
      name: 'Crossbow, light',
      melee: false,
      damage: '1d8',
      damage_type: 'piercing',
      properties: ['ammunition (range 80/320)', 'loading', 'two-handed'],
    },
    dart: {
      name: 'Dart',
      melee: false,
      damage: '1d4',
      damage_type: 'piercing',
      properties: ['finesse', 'thrown (range 20/60)'],
    },
    shortbow: {
      name: 'Shortbow',
      melee: false,
      damage: '1d6',
      damage_type: 'piercing',
      properties: ['ammunition (range 80/320)', 'two-handed'],
    },
    sling: {
      name: 'Sling',
      melee: false,
      damage: '1d4',
      damage_type: 'bludgeoning',
      properties: ['ammunition (range 30/120)'],
    },
  },
  martial_melee: {
    battleaxe: {
      name: 'Battleaxe',
      melee: true,
      damage: '1d8',
      damage_type: 'slashing',
      properties: ['versatile (1d10)'],
    },
    flail: {
      name: 'Flail',
      melee: true,
      damage: '1d8',
      damage_type: 'bludgeoning',
      properties: [],
    },
    glaive: {
      name: 'Glaive',
      melee: true,
      damage: '1d10',
      damage_type: 'slashing',
      properties: ['heavy', 'reach', 'two-handed'],
    },
    greataxe: {
      name: 'Greataxe',
      melee: true,
      damage: '1d12',
      damage_type: 'slashing',
      properties: ['heavy', 'two-handed'],
    },
    greatsword: {
      name: 'Greatsword',
      melee: true,
      damage: '2d6',
      damage_type: 'slashing',
      properties: ['heavy', 'two-handed'],
    },
    halberd: {
      name: 'Halberd',
      melee: true,
      damage: '1d10',
      damage_type: 'slashing',
      properties: ['heavy', 'reach', 'two-handed'],
    },
    lance: {
      name: 'Lance',
      melee: true,
      damage: '1d12',
      damage_type: 'piercing',
      properties: ['reach, special'],
    },
    longsword: {
      name: 'Longsword',
      melee: true,
      damage: '1d8',
      damage_type: 'slashing',
      properties: ['versatile (1d10)'],
    },
    maul: {
      name: 'Maul',
      melee: true,
      damage: '2d6',
      damage_type: 'bludgeoning',
      properties: ['heavy', 'two-handed'],
    },
    morningstar: {
      name: 'Morningstar',
      melee: true,
      damage: '1d8',
      damage_type: 'piercing',
      properties: [],
    },
    pike: {
      name: 'Pike',
      melee: true,
      damage: '1d10',
      damage_type: 'slashing',
      properties: ['heavy', 'reach', 'two-handed'],
    },
    rapier: {
      name: 'Rapier',
      melee: true,
      damage: '1d8',
      damage_type: 'piercing',
      properties: ['finesse'],
    },
    scimitar: {
      name: 'Scimitar',
      melee: true,
      damage: '1d6',
      damage_type: 'slashing',
      properties: ['finesse', 'light'],
    },
    shortsword: {
      name: 'Shortsword',
      melee: true,
      damage: '1d6',
      damage_type: 'piercing',
      properties: ['finesse', 'light'],
    },
    trident: {
      name: 'Trident',
      melee: true,
      damage: '1d6',
      damage_type: 'piercing',
      properties: ['thrown (range 20/60)', 'versatile (1d8)'],
    },
    war_pick: {
      name: 'War pick',
      melee: true,
      damage: '1d8',
      damage_type: 'piercing',
      properties: [],
    },
    warhammer: {
      name: 'Warhammer',
      melee: true,
      damage: '1d8',
      damage_type: 'bludegeoning',
      properties: ['versatile (1d10)'],
    },
    whip: {
      name: 'Whip',
      melee: true,
      damage: '1d4',
      damage_type: 'slashing',
      properties: ['finesse', 'reach'],
    },
  },
  martial_range: {
    blowgun: {
      name: 'Blowgun',
      melee: false,
      damage: '1',
      damage_type: 'piercing',
      properties: ['ammunition (range 25/100)', 'loading'],
    },
    hand_crossbow: {
      name: 'Crossbow, hand',
      melee: false,
      damage: '1d6',
      damage_type: 'piercing',
      properties: ['ammunition (range 30/120)', 'light', 'loading'],
    },
    heavy_crossbow: {
      name: 'Crossbow, heavy',
      melee: false,
      damage: '1d10',
      damage_type: 'piercing',
      properties: [
        'ammunition (range 100/400)',
        'heavy',
        'loading',
        'two-handed',
      ],
    },
    longbow: {
      name: 'Longbow',
      melee: false,
      damage: '1d8',
      damage_type: 'piercing',
      properties: ['ammunition (range 150/600)', 'heavy', 'two-handed'],
    },
    net: {
      name: 'Net',
      melee: false,
      damage: '',
      damage_type: '',
      properties: ['special', 'thrown (range 5/15)'],
    },
  },
};
